# Cache maven cache directory so external artifacts dont need to be re-downloaded.
cache:
  directories:
  - $HOME/.m2

language: java

jdk:
  - oraclejdk8

notifications:
  email: false

script:
  - |
    # TRAVIS_BRANCH is name of the branch built OR the name of the target branch in case of PRs
    if [ "$TRAVIS_BRANCH" == "master" -a -z "$TRAVIS_PULL_REQUEST_BRANCH" ]; then
      echo "Run sonar analysis for master only"
      jacoco_goal="org.jacoco:jacoco-maven-plugin:prepare-agent"
      sonar_goal="org.sonarsource.scanner.maven:sonar-maven-plugin:3.7.0.1746:sonar"
      sonar_opts="-Dsonar.projectKey=jenkins_ws-cleanup-plugin"
    else
      echo "Skipping sonar analysis"
    fi
    mvn -B clean $jacoco_goal install $sonar_goal $sonar_opts

# disable sudo to ensure that this build runs on the travis container-based
# infrastructure. This should prevent the buffer overflow from
# https://github.com/travis-ci/travis-ci/issues/5227
sudo: false

# due to travis-ci changes in default build environment,
# this must be specify in order for oraclejdk8 to install
# https://blog.travis-ci.com/2019-04-15-xenial-default-build-environment
dist: trusty

addons:
  sonarcloud: # Report coverage results to sonarcloud.io
    organization: "olivergondza"
    token:
      secure: "nJd5oVtwVHIEDPvRVfuW7ZpKl6VNtQoizkkBEnfJJ4vF8MJAQn2JPZ8XMyPQuYOBgiYp9+3lryoqKd4fE26uB8TQ0cRKKh+ISpCNrKzfDcppTCdEZVCM6P0JqSBYFjuz26c4NEyCqrnAVL6GVXhb8ByfAR9tsVfDvtNu2Bil+Ik="
